### ISSUE TITLE
Error while creating connection to Compute Service - ArgumentError: wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by nikitsaraf** [fog/fog-softlayer#64]
```
○ cat ~/.fog
default:
  softlayer_username: SL_USERNAME
  softlayer_api_key: SL_API_KEY
  softlayer_default_domain: SL_DOMAIN_NAME
  softlayer_cluster: cluster
```
On doing the following:-
```
require 'fog/softlayer'
@sl = Fog::Compute[:softlayer]
```
It throws the following error:-
```
ArgumentError: wrong number of arguments (2 for 1)
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.25.0/lib/fog/core/service.rb:192:in `request'
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-softlayer-0.4.6/lib/fog/softlayer/compute.rb:79:in `<class:Softlayer>'
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-softlayer-0.4.6/lib/fog/softlayer/compute.rb:12:in `<module:Compute>'
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-softlayer-0.4.6/lib/fog/softlayer/compute.rb:11:in `<module:Fog>'
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-softlayer-0.4.6/lib/fog/softlayer/compute.rb:10:in `<top (required)>'
	from ~/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:69:in `require'
	from ~/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:69:in `require'
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.25.0/lib/fog/compute.rb:55:in `new'
	from ~/.rvm/gems/ruby-1.9.3-p547/gems/fog-core-1.25.0/lib/fog/compute.rb:4:in `[]'
	from (irb):2
	from ~/.rvm/rubies/ruby-1.9.3-p547/bin/irb:12:in `<main>'
```
